title: Raunak CSA Blog
description: "August 2023 to June 2024"
owner_name: Raunak Mondal
github_username: Raunak Mondal
github_repo: "better-csa-pages"
baseurl: "/raunak"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/raunak2007"}

# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
